#!/bin/bash

echo "Exporting temp policies..."
/usr/local/bin/akp -e /var/tmp/AirKeeperSettings-temp_apt.plist

echo "Restoring all changed policies..."
/usr/local/bin/akp -r

killall -9 Preferences || true

exit 0
